### ---- Prompt -------------------
format = """
$username\
$hostname\
$directory\
$git_branch\
$character
"""
right_format="""
$all
"""
 
add_newline = false

### ---- Basic config -------------

[directory]
style = "bold cyan"
read_only = " ğŸ”’"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[â¯](cyan)"
error_symbol = "[â¯](red)"
# vicmd_symbol = "[â®](green)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

### ---- Git config -------------------

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch]($style) "
style = "green"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "green"

[git_metrics]
disabled = false

### ---- Language specific configs -------------

[c]
format = '[$name $version]($style) '

[python]
format = "[$symbol($version )($virtualenv )]($style)"
symbol = "îˆµ "

[java]
style="bold red"
format = "[$symbol($version )]($style)"
symbol = "î‰– "

[nodejs]
format = "[$symbol($version )]($style)"


### ---- Others -------------------












